# PRACTICA INDEPEDIENTE 

In [26]:
# Leemos los datos y seteamos el datetime como índice.
import numpy as np
import pandas as pd

bikes = pd.read_csv('../Data/bikeshare.csv', index_col='datetime', parse_dates=True)

In [27]:
# Dado que "count" es un método de pandas, es conviente renombrar la columna:

bikes.rename(columns={'count':'total'}, inplace=True)

In [47]:
bikes.head()


season  holiday  workingday  weather  temp   atemp  \
datetime                                                                  
2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
2011-01-01 01:00:00       1        0           0        1  9.02  13.635   
2011-01-01 02:00:00       1        0           0        1  9.02  13.635   
2011-01-01 03:00:00       1        0           0        1  9.84  14.395   
2011-01-01 04:00:00       1        0           0        1  9.84  14.395   

                     humidity  windspeed  casual  registered  ...  15  16  17  \
datetime                                                      ...               
2011-01-01 00:00:00        81        0.0       3          13  ...   0   0   0   
2011-01-01 01:00:00        80        0.0       8          32  ...   0   0   0   
2011-01-01 02:00:00        80        0.0       5          27  ...   0   0   0   
2011-01-01 03:00:00        75        0.0       3          10  ...   0   0   0   
2011-01-01 04:00:00        75        0.0       0           1  ...   0   0   0   

                     18  19  20  21  22  23   temp_2  
datetime                                              
2011-01-01 00:00:00   0   0   0   0   0   0  96.8256  
2011-01-01 01:00:00   0   0   0   0   0   0  81.3604  
2011-01-01 02:00:00   0   0   0   0   0   0  81.3604  
2011-01-01 03:00:00   0   0   0   0   0   0  96.8256  
2011-01-01 04:00:00   0   0   0   0   0   0  96.8256  

[5 rows x 37 columns]

##  Adicionales

### Ingeniería de features

Vea si puede crear las siguientes features:

- ** hora: ** como una sola feature numérica (de 0 a 23)
- ** hora: ** como una feature categórica (use 23 variables dummy)
- ** día: ** como una sola feature categórica (día = 1 de 7am a 8pm y día = 0 de lo contrario)


In [29]:
# hora como variable numérica
bikes['hora'] = bikes.index.hour

In [30]:
bikes['hora'].values

array([ 0,  1,  2, ..., 21, 22, 23], dtype=int64)

In [31]:
# hora como categorica
bikes_dummies = pd.get_dummies(bikes.index.hour, drop_first=True)

In [32]:
bikes_dummies.head()

1   2   3   4   5   6   7   8   9   10  ...  14  15  16  17  18  19  20  \
0   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
1   1   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
2   0   1   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
3   0   0   1   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
4   0   0   0   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   

   21  22  23  
0   0   0   0  
1   0   0   0  
2   0   0   0  
3   0   0   0  
4   0   0   0  

[5 rows x 23 columns]

In [33]:
bikes_dummies.index = bikes.index

In [34]:
bikes_dummies.sample(5)

1   2   3   4   5   6   7   8   9   10  ...  14  15  16  \
datetime                                                     ...               
2011-09-15 17:00:00   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   
2012-02-09 18:00:00   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   
2012-05-15 00:00:00   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   
2012-07-15 11:00:00   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   
2012-01-05 07:00:00   0   0   0   0   0   0   1   0   0   0  ...   0   0   0   

                     17  18  19  20  21  22  23  
datetime                                         
2011-09-15 17:00:00   1   0   0   0   0   0   0  
2012-02-09 18:00:00   0   1   0   0   0   0   0  
2012-05-15 00:00:00   0   0   0   0   0   0   0  
2012-07-15 11:00:00   0   0   0   0   0   0   0  
2012-01-05 07:00:00   0   0   0   0   0   0   0  

[5 rows x 23 columns]

In [35]:
# días como categórica
a = np.array(((bikes.index.hour) >= 7) & (bikes.index.hour <= 20))
a

array([False, False, False, ..., False, False, False])

In [36]:
bikes['dia']= a.astype(int)
bikes['dia'].values

array([0, 0, 0, ..., 0, 0, 0])

In [37]:
bikes['dia'].sample(5)

datetime
2011-09-16 21:00:00    0
2011-11-18 17:00:00    1
2012-05-04 06:00:00    0
2011-03-16 10:00:00    1
2011-05-18 21:00:00    0
Name: dia, dtype: int32

In [38]:
bikes  = pd.concat([bikes,bikes_dummies], axis = 1)

In [39]:
bikes.head()

season  holiday  workingday  weather  temp   atemp  \
datetime                                                                  
2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
2011-01-01 01:00:00       1        0           0        1  9.02  13.635   
2011-01-01 02:00:00       1        0           0        1  9.02  13.635   
2011-01-01 03:00:00       1        0           0        1  9.84  14.395   
2011-01-01 04:00:00       1        0           0        1  9.84  14.395   

                     humidity  windspeed  casual  registered  ...  14  15  16  \
datetime                                                      ...               
2011-01-01 00:00:00        81        0.0       3          13  ...   0   0   0   
2011-01-01 01:00:00        80        0.0       8          32  ...   0   0   0   
2011-01-01 02:00:00        80        0.0       5          27  ...   0   0   0   
2011-01-01 03:00:00        75        0.0       3          10  ...   0   0   0   
2011-01-01 04:00:00        75        0.0       0           1  ...   0   0   0   

                     17  18  19  20  21  22  23  
datetime                                         
2011-01-01 00:00:00   0   0   0   0   0   0   0  
2011-01-01 01:00:00   0   0   0   0   0   0   0  
2011-01-01 02:00:00   0   0   0   0   0   0   0  
2011-01-01 03:00:00   0   0   0   0   0   0   0  
2011-01-01 04:00:00   0   0   0   0   0   0   0  

[5 rows x 36 columns]

##### A continuación, pruebe utilizar cada una de las tres features con `train_test_rmse` para ver cuál funciona mejor!

In [40]:
from sklearn.linear_model import LinearRegression
from sklearn import metrics

In [41]:
# Definimos una función que acepta una lista de features, hace el split entre train y test,
# reservando un 25% de las observaciones para testeo, y devuelve la prueba RMSE.

from sklearn.model_selection import train_test_split

def train_test_rmse(feature_cols):
    X = bikes[feature_cols]
    y = bikes.total
    # Como estamos trabajando con observaciones ordenadas en el tiempo, ponemos
    # shuffle=False para evitar data leakage
    X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle=False)
    linreg = LinearRegression()
    linreg.fit(X_train, y_train)
    y_pred = linreg.predict(X_test)
    return np.sqrt(metrics.mean_squared_error(y_test, y_pred))

In [42]:
train_test_rmse(['temp', 'season', 'humidity'])

208.60652132566102

In [43]:
train_test_rmse(['temp', 'season', 'humidity','dia'])

177.27663881641251

In [44]:
train_test_rmse(['temp', 'season', 'humidity','hora'])

197.75102530844302

In [45]:
train_test_rmse(['temp', 'season', 'humidity',1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23])

153.94217999442378

RMSE es la raiz cuadradada de la media de los errores al cuadrado. Por lo tanto el mejor modelo es el ultimo porque tiene menor error.

### Crear y comparar modelos con variables cuadráticas

¿Con cuales variables probaría? 

In [48]:
bikes['temp_2'] = bikes.temp ** 2

In [49]:
bikes['humidity_2'] = bikes.humidity ** 2

In [50]:
train_test_rmse(['temp', 'season', 'humidity',1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,
               'temp_2', 'humidity_2'])

153.2818367679594

Vemos que agregando dos variables cuadráticas disminuyó levemente el valor de RMSE respecto del mejor modelo sin variables cuadráticas.